= Data Model Mapping
:toc:
:cj: Connected JSON

Mapping XML, JSON, GraphML, Connected JSON.

.GraphML
- key-data
- custom attributes
- custom XML tags as `<data>` values -- need to transport XML namespace

.Connected JSON
- custom JSON in each object

.Variants
XML -> GraphML -> Gio -> GraphML -> XML

XML -> GraphML -> Gio -> CJ -> JSON

JSON -> CJ -> Gio -> GraphML -> XML

JSON -> CJ -> Gio -> CJ -> JSON

== Graphml Custom Attributes in ANY element

.GraphML
----
<graphml
  xmlns:my="http://example.org/my"
>
    <node my:foo="bar"> ... </node>
----

.CJ
----
{
    "namespaces": {
        "my": "http://example.org/my"
    },
...
    "node": {
        "customAttributes": {
            "my:foo": "bar"
        }
    }

}
----

== Graphml Custom Attributes in `<key>` element

----
<key id="d12" for="node" attr.name="PortViewState" y:attr.uri="http://www.yworks.com/xml/yfiles-common/2.0/folding/1.1/PortViewState" />
----

- `d12` is considered synthetic
- `for="node"` can be computed
- `attr.name="PortViewState"` the name must be kept -> JSON property key

.CJ
----
{
    "namespaces": {
        "my": "http://example.org/my"
    },
...
    "node": {
        "PortViewState": ...
        "customKeyAttributes": {
               "y:attr.uri"="http://www.yworks.com/xml/yfiles-common/2.0/folding/1.1/PortViewState"
        }
    }

}
----

namespaces::
A JSON object with namespace prefixes as keys.
The values are the namespace URIs.

customAttributes::
A JSON object with custom attributes as keys.
The values are the attribute values.
The keys are prefixed with the namespace URI, e.g., `my:foo`.

customKeyAttributes::
This represents the special case of the special case:
Custom XML attributes on an element, which itself is not represented in {cj}.
We have a GraphML `<key>` element with custom attributes.
A key has a `for` attribute with a value of `graph`, `node`, `edge`, `hyperedge`, `port`, `endpoint` or `all`.

These attributes are stored in the corresponding {cj} element, where the `<data>` tag is used.
In that element, the property `customKeyAttributes` is a JSON object with the attribute names as keys and the attribute values as values.
The keys are prefixed with the namespace URI.

== Graphml `<key>`

The data model of `<key>` is

[cols="2,1,3"]
|===
| XML | Type | Desc

| attribute `id` | string | used by `<data key="...">`

| attribute `attr.name` | string | the name of the attribute

| attribute `attr.type` | enum | one of `string`, `int`, `long`, `float`, `double`, `boolean`

| attribute `for` | enum | one of `graph`, `node`, `edge`, `hyperedge`, `port`, `endpoint` or `all`

| child element `<default>` | XML | the default value of the attribute

| custom attributes | string | ...
|===

which can be mapped to this JSON

.JSON to represent `<key>` info from Graphml
[source,json5]
----
{
    // key @id
    "someId1": {
      // key @attr.name
      "attr.name": "...",
      // key @attr.type
      "attr.type": "string",
      // key <default>
      "default": "...some XML..."
    },
    "someId2": {}
}
----

which is document-level meta-data.

.Embedding `<key>` info in {cj}
[source,json5]
----
{
  "connectedJson": {
    "versionDate": "2025-07-14",
    "versionNumber": "5.0.0"
  },
  "data": {
    "graphml:keys": {
        "someId1": {
            "attr.name": "...",
            "attr.type": "string",
            "default": "...some XML..."
        },
        "someId2": {}
    }
  },
  "graphs": [
    // graph
  ]
}
----


== Chains

.We start with GraphMl
[source,xml]
----
<graphml>

    <!-- Attributes for nodes -->
    <key id="ext_in" for="node" attr.name="is_ext"
       attr.type="boolean"><default>true</default></key>
    <key id="neuron_type" for="node" attr.name="model"
       attr.type="string"><default>leaky</default></key>
    <!-- ... and -->
    <node id="N1">
        <data key="neuron_type">leaky</data>
        <!-- just implied; -->
        <data key="ext_in">true</data>
    </node>
</graphml>
----

.Logically it's this
|===
| Entity | Attr.name | value | Attr.type | Key Id

| N1 | model | leaky | string e| neuron_type
| N1 | is_ext | true | boolean e| ext_in
|===

.Represented in {cj}
[source,json]
----
{
  "data": {
    "graphml:keys": {
      "ext_in": { "for": "node", "attr.name": "is_ext",
        "attr.type": "boolean", "default": "true" },
      "neuron_type": { "for": "node", "attr.name": "model",
        "attr.type": "string", "default": "leaky" }
    }
  },
  "graphs": [ {
    "nodes": [
      {
        "id": "N1",
        "data": {
          "model": "leaky",
          "is_ext": true
        }
      }
    ]
  } ]
}
----

