---
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: [http://localhost:8080]
    description: Generated server url
paths:
  "/api/validate":
    post:
      tags:
        - graphml-controller
      operationId: validate
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
          application/xml:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
          text/plain:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                "$ref": "#/components/schemas/StreamingResponseBody"
  "/api/read":
    post:
      tags:
        - graphml-controller
      operationId: read
      parameters:
        - name: type
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
          application/xml:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
          text/plain:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                "$ref": "#/components/schemas/StreamingResponseBody"
components:
  schemas:
    StreamingResponseBody:
      type: object
