<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <artifactId>graphinout</artifactId>
        <groupId>com.graphinout</groupId>
        <version>0.1.14</version>
    </parent>

    <artifactId>foundation-emulation</artifactId>
    <name>foundation-emulation</name>
    <description>
        Foundation is in general a dependency-free base layer for Java projects.
        Foundation has four layers: 'emulation', 'pure', 'shared', 'jvm'.

        ⚪️Emulation: Stripped down annotations (jspecify, Jackson). For 2cl-compiler. Java 8 syntax and JRE.
        ⚪️Pure: No dependencies (except on 'emulation'), only classes from the j2cl compatible fragment. Java 8 syntax.
        ⚪️Shared: Only j2cl-dependencies allowed (e.g. elements). Java 8 syntax and JRE.
        ⚪️JVM: This code cannot j2cl-compile. Any java syntax.

        See foundation-pure/README.adoc for details.
    </description>

    <properties>
        <!-- current j2cl version is Java 8 syntax. See j2cl.adoc -->
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
    </properties>

    <dependencies>
        <!-- we inlined (copied) the jspecify annotations and removed the MODULE enum value -->
        <!--        <dependency><groupId>org.jspecify</groupId><artifactId>jspecify</artifactId><optional>true</optional></dependency>-->
        <!--        <dependency><groupId>org.jspecify</groupId><artifactId>jspecify</artifactId>-->
        <!--            <classifier>sources</classifier>-->
        <!--        </dependency>-->

        <!-- Do not supply the sources. Jackson annotation sources used too many non-j2cl dependencies -->
<!--       <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-annotations</artifactId>-->
<!--            <version>2.20</version>-->
<!--       </dependency>-->
        <!-- jackson annotation sources used too many non-j2cl dependencies -->
<!--        <dependency><groupId>com.fasterxml.jackson.core</groupId><artifactId>jackson-annotations</artifactId>-->
<!--            <classifier>sources</classifier>-->
<!--            <version>2.20</version>-->
<!--        </dependency>-->

    </dependencies>

    <build>
        <resources>
            <!-- bundle sources with the main jar, so they are visible to j2cl -->
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.java</include>
                </includes>
                <filtering>false</filtering>
            </resource>
            <!-- keep default resources -->
            <resource>
                <directory>src/main/resources</directory>
                <filtering>false</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>${j2cl-mp-group}</groupId><artifactId>${j2cl-mp-artifact}</artifactId>
                <version>${j2cl-mp-version}</version>
                <executions><execution>
                    <phase>compile</phase>
                    <goals><goal>build</goal></goals>
                </execution></executions>
                <configuration>
                    <webappDirectory>${project.basedir}/target/webapp</webappDirectory>
                    <initialScriptFilename>j2cl-result.js</initialScriptFilename>
                    <enableSourcemaps>${j2cl-mp-enableSourceMaps}</enableSourcemaps>
                    <compilationLevel>${j2cl-mp-compilationLevel}</compilationLevel>
                </configuration>
            </plugin>

        </plugins>
    </build>


</project>
